server:
  port: 20912

spring:
  profiles:
    active: druid

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml


logging:
  level:
    com.m3.fzo.hy: debug

Token:
  sing: abcdefghrgklmnopqistuvwxyz
  expire: 1800000
